services:
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: streampulse-kafka
    ports:
      - "9092:9092"
    environment:
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_HEAP_OPTS: "-Xms256m -Xmx256m"
    healthcheck:
      test:
        - CMD-SHELL
        - >-
          kafka-topics --bootstrap-server localhost:9092 --create --if-not-exists
          --topic flight-live-positions --partitions 1 --replication-factor 1
          >/dev/null 2>&1 &&
          kafka-topics --bootstrap-server localhost:9092 --describe
          --topic flight-live-positions 2>/dev/null | grep -q 'Leader: 1'
      interval: 10s
      timeout: 5s
      retries: 18
      start_period: 30s

  opensearch:
    image: opensearchproject/opensearch:2.11.0
    container_name: streampulse-opensearch
    environment:
      - cluster.name=streampulse-cluster
      - node.name=opensearch-node1
      - discovery.type=single-node
      - "DISABLE_SECURITY_PLUGIN=true"
      - "OPENSEARCH_JAVA_OPTS=-Xms256m -Xmx256m"
    ports:
      - "9200:9200"
      - "9600:9600"